<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
?>

<div class="block block-search">
  <div class="block block-title"><strong>
    <?php /* @escapeNotVerified */ echo __('Search'); ?>
    </strong></div>
  <div class="block block-content">
    <form class="form minisearch" id="search_mini_form" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
      <div class="field search">
        <label class="label" for="search" data-role="minisearch-label"> <span>
          <?php /* @escapeNotVerified */ echo __('Search'); ?>
          </span> </label>
        <div class="control">
          <input id="search"
                           data-mage-init='{"quickSearch":{
                                "formSelector":"#search_mini_form",
                                "url":"<?php /* @escapeNotVerified */ echo $block->getUrl('search/ajax/suggest', ['_secure' => $block->getRequest()->isSecure()]); ?>",
                                "destinationSelector":"#search_autocomplete"}
                           }'
                           type="text"
                           name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
                           value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>"
                           placeholder="<?php /* @escapeNotVerified */ echo __('Search '); ?>"
                           class="input-text"
                           maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength();?>"
                           role="combobox"
                           aria-haspopup="false"
                           aria-autocomplete="both"
                           autocomplete="off"/>
          <button type="submit"
                        title="<?php echo $block->escapeHtml(__('Search')) ?>"
                        class="action search"> <span><i class="fa fa-search" aria-hidden="true"></i></span> </button>
          <div id="search_autocomplete" class="search-autocomplete"></div>
          <?php echo $block->getChildHtml() ?> </div>
          <div class="mb">
          <div class="wsh">
          <a href="#"><i class="fa fa-heart-o" aria-hidden="true"></i></a>
          </div>
        <div class="sign-inimg">
          <p> sign in <span><img src=" <?php echo $block->getViewFileUrl('/images/userl.png'); ?>" class="nrml-userimg"> <img src="<?php echo $block->getViewFileUrl('/images/userhl.png'); ?>" class="hover-userimg"> </span> </p>
          <div class="login-data">
            <ul>
              <li> <i class="fa fa-user-o" aria-hidden="true"></i> <a href="<?php echo $block->getUrl('customer/account') ?>">your account</a> </li>
              <li> <i class="fa fa-cube" aria-hidden="true"></i> <a href="<?php echo $block->getUrl('customer/account') ?>">your orders</a> </li>
              <li> <i class="fa fa-heart-o" aria-hidden="true"></i> <a href="<?php echo $block->getUrl('wishlist') ?>">wishlist</a> </li>
            </ul>
            <p class="new-user"> If you are a new user</p>
            <a href="<?php echo $block->getUrl('customer/account/create') ?>" id="customer_register_link">register</a> <a href="<?php echo $block->getUrl('customer/account/login') ?>" id="customer_login_link">Log in</a> </div>
        </div>
      </div>
      </div>
    </form>
  </div>
</div>
